# data/data_loader.py
"""
Robust Excel-based data loader for HIV regimen optimization.
"""

import os
import pandas as pd
import logging
from typing import Dict, List

_logger = logging.getLogger(__name__)


def load_drug_data() -> Dict[str, Dict]:
    """Load drug properties and resistance profiles from Excel."""
    # drugs_sourced.xlsx is GENERATED by apply_sourced_costs.py. Fall back to
    # the original table so a fresh clone works before the generators are run;
    # warn, because the fallback carries the unsourced cost figures.
    DRUGS_FILE = 'data/drugs_sourced.xlsx'
    if not os.path.exists(DRUGS_FILE):
        DRUGS_FILE = 'data/drugs.xlsx'
        _logger.warning("data/drugs_sourced.xlsx not found -- falling back to "
                        "drugs.xlsx, which carries UNSOURCED costs. "
                        "Run: python apply_sourced_costs.py")
    if not os.path.exists(DRUGS_FILE):
        raise FileNotFoundError(f"Drugs Excel file not found: {DRUGS_FILE}")
    
    try:
        # Load Drugs sheet
        df_drugs = pd.read_excel(DRUGS_FILE, sheet_name='Drugs')
        required = ['Drug', 'Class', 'Efficacy', 'Toxicity', 'Monthly_Cost_USD']
        for col in required:
            if col not in df_drugs.columns:
                raise ValueError(f"Missing column in Drugs sheet: {col}")
        
        drug_data = {}
        for _, row in df_drugs.iterrows():
            drug = str(row['Drug']).strip()
            if not drug: continue
            drug_data[drug] = {
                'Class': str(row['Class']).strip(),
                'Efficacy': float(row['Efficacy']),
                'Toxicity': float(row['Toxicity']),
                'Liver_Impact': float(row.get('Liver_Impact', 0.0)),
                'Kidney_Impact': float(row.get('Kidney_Impact', 0.0)),
                'Monthly_Cost_USD': float(row['Monthly_Cost_USD']),
                'Contraindications': _parse_list(row.get('Contraindications', '')),
                'Side_Effects': _parse_list(row.get('Side_Effects', ''))
            }
        
        # Load Resistance sheet
        df_res = pd.read_excel(DRUGS_FILE, sheet_name='Resistance')
        resistance_map = {}
        for _, row in df_res.iterrows():
            mut = str(row['Mutation']).strip()
            drug = str(row['Drug']).strip()
            red = float(row['Efficacy_Reduction'])
            if drug not in resistance_map:
                resistance_map[drug] = {}
            resistance_map[drug][mut] = red
        
        for drug in drug_data:
            drug_data[drug]['Resistance_Reduction'] = resistance_map.get(drug, {})
        
        _logger.info("Loaded %d drugs from %s", len(drug_data), DRUGS_FILE)
        return drug_data
    
    except Exception as e:
        _logger.error("Error loading %s: %s", DRUGS_FILE, e)
        raise


def load_patient_profiles() -> List[Dict]:
    """Load patient profiles from Excel."""
    # AllPatients_v2.xlsx is GENERATED by regenerate_patients.py. Fall back to
    # the base cohort so a fresh clone works; warn, because the fallback lacks
    # the sourced formulary tiers.
    PATIENTS_FILE = 'data/AllPatients_v2.xlsx'
    if not os.path.exists(PATIENTS_FILE):
        PATIENTS_FILE = 'data/AllPatients.xlsx'
        _logger.warning("data/AllPatients_v2.xlsx not found -- falling back to "
                        "AllPatients.xlsx, without formulary tiers. "
                        "Run: python regenerate_patients.py")
    if not os.path.exists(PATIENTS_FILE):
        raise FileNotFoundError(f"Patients Excel file not found: {PATIENTS_FILE}")
    
    try:
        df = pd.read_excel(PATIENTS_FILE)
        required = ['Patient_ID', 'Mutations', 'Liver_Function', 'Kidney_Function']
        for col in required:
            if col not in df.columns:
                raise ValueError(f"Missing column in patients.xlsx: {col}")
        
        profiles = []
        for _, row in df.iterrows():
            if pd.isna(row['Patient_ID']): continue
            profile = {
                'Patient_ID': str(row['Patient_ID']).strip(),
                'Mutations': _parse_list(row['Mutations']),
                'Liver_Function': float(row['Liver_Function']),
                'Kidney_Function': float(row['Kidney_Function']),
                'Pregnancy': str(row.get('Pregnancy', 'No')).strip().lower() == 'yes',
                'Cost_Sensitivity': str(row.get('Cost_Sensitivity', 'Medium')).title(),
                'Comorbidities': _parse_list(row.get('Comorbidities', '')),
                'Allergies': _parse_list(row.get('Allergies', '')),
                'Access_Constraints': _parse_list(row.get('Access_Constraints', ''))
            }
            if 'Formulary_Tier' in df.columns and not pd.isna(row.get('Formulary_Tier')):
                profile['Formulary_Tier'] = str(row['Formulary_Tier']).strip()
            profiles.append(profile)
        
        _logger.info("Loaded %d patients from %s", len(profiles), PATIENTS_FILE)
        return profiles
    
    except Exception as e:
        _logger.error("Error loading %s: %s", PATIENTS_FILE, e)
        raise


def _parse_list(value):
    """Parse comma/space-separated string into clean list."""
    if pd.isna(value) or str(value).strip() == '':
        return []
    items = [item.strip() for item in str(value).replace(',', ' ').split()]
    return [item for item in items if item]